name: Docs Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.2

    - name: Vuepress Deploy
      uses: jenkey2011/vuepress-deploy@v1.8.1
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BUILD_SCRIPT: npm install && npm run build
        BUILD_DIR: docs/.vuepress/dist/
